AWSTemplateFormatVersion: '2010-09-09'
Description: Setup for containerized RAG Lambda with API Gateway (Async Processing)

Parameters:
  ProjectName:
    Type: String
    Default: rag-lambda

  CreateECR:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: Whether to create the ECR repository

  LambdaImageUri:
    Type: String
    Description: URI of the container image in ECR (e.g., 123456789012.dkr.ecr.eu-west-1.amazonaws.com/rag-lambda:latest)
    Default: "661920085301.dkr.ecr.eu-west-1.amazonaws.com/rag-container:latest"

  ApiGatewayStage:
    Type: String
    Default: "prod"
    Description: API Gateway deployment stage

  EnableCORS:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"
    Description: Whether to enable CORS for the API

  JobTTLHours:
    Type: Number
    Default: 24
    Description: Hours to keep job results in DynamoDB

Conditions:
  CreateECRCondition: !Equals [!Ref CreateECR, "true"]
  EnableCORSCondition: !Equals [!Ref EnableCORS, "true"]

Resources:

  ### ECR Repository ###
  RAGLambdaECR:
    Type: AWS::ECR::Repository
    Condition: CreateECRCondition
    Properties:
      RepositoryName: !Ref ProjectName

  ### DynamoDB Table for Job Status ###
  JobStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-job-status
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ### IAM Role for Lambda Execution ###
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sagemaker:InvokeEndpoint
                  - bedrock:InvokeModel
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}"

  ### Main Lambda Function (Container Image) ###
  RAGLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref ProjectName
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref LambdaImageUri
      Timeout: 900
      MemorySize: 2048
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT_NAME: embedding-endpoint
          MILVUS_HOST: 34.241.177.15
          MILVUS_PORT: "19530"
          MILVUS_COLLECTION: cssf_documents_final_final
          BEDROCK_REGION: us-east-1
          IRELAND_REGION: eu-west-1
          VERSION_TIMESTAMP: "2025-06-17T15:30:00Z"
          JOB_STATUS_TABLE: !Ref JobStatusTable
          JOB_TTL_HOURS: !Ref JobTTLHours

  ### API Gateway REST API ###
  RAGRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${ProjectName}-api
      Description: REST API for RAG Lambda function with async processing
      EndpointConfiguration:
        Types:
          - REGIONAL
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: execute-api:Invoke
            Resource: '*'

  ### API Gateway Resource for Query ###
  RAGApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RAGRestApi
      ParentId: !GetAtt RAGRestApi.RootResourceId
      PathPart: query

  ### API Gateway Resource for Status ###
  StatusApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RAGRestApi
      ParentId: !GetAtt RAGRestApi.RootResourceId
      PathPart: status

  ### API Gateway Resource for Status with JobId ###
  StatusJobApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RAGRestApi
      ParentId: !Ref StatusApiResource
      PathPart: "{jobId}"

  ### API Gateway Method (POST) for Query Submission ###
  RAGApiMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RAGRestApi
      ResourceId: !Ref RAGApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RAGLambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: !If [EnableCORSCondition, "'*'", !Ref "AWS::NoValue"]
            method.response.header.Access-Control-Allow-Headers: !If [EnableCORSCondition, "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'", !Ref "AWS::NoValue"]
            method.response.header.Access-Control-Allow-Methods: !If [EnableCORSCondition, "'POST,OPTIONS'", !Ref "AWS::NoValue"]

  ### API Gateway Method (GET) for Status Check ###
  StatusApiMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RAGRestApi
      ResourceId: !Ref StatusJobApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RAGLambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: !If [EnableCORSCondition, "'*'", !Ref "AWS::NoValue"]
            method.response.header.Access-Control-Allow-Headers: !If [EnableCORSCondition, "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'", !Ref "AWS::NoValue"]
            method.response.header.Access-Control-Allow-Methods: !If [EnableCORSCondition, "'GET,OPTIONS'", !Ref "AWS::NoValue"]

  ### API Gateway Method (GET) for Health Check ###
  HealthApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RAGRestApi
      ParentId: !GetAtt RAGRestApi.RootResourceId
      PathPart: health

  HealthApiMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RAGRestApi
      ResourceId: !Ref HealthApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RAGLambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: !If [EnableCORSCondition, "'*'", !Ref "AWS::NoValue"]

  ### CORS OPTIONS Methods ###
  RAGApiMethodOptions:
    Type: AWS::ApiGateway::Method
    Condition: EnableCORSCondition
    Properties:
      RestApiId: !Ref RAGRestApi
      ResourceId: !Ref RAGApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  StatusApiMethodOptions:
    Type: AWS::ApiGateway::Method
    Condition: EnableCORSCondition
    Properties:
      RestApiId: !Ref RAGRestApi
      ResourceId: !Ref StatusJobApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  ### Lambda Permission for API Gateway ###
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RAGLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RAGRestApi}/*/*

  ### API Gateway Deployment ###
  RAGApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RAGApiMethodPost
      - StatusApiMethodGet
      - HealthApiMethodGet
    Properties:
      RestApiId: !Ref RAGRestApi
      StageName: !Ref ApiGatewayStage
      Description: !Sub Deployment for ${ProjectName} API

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt RAGLambdaFunction.Arn
    Export:
      Name: !Sub ${ProjectName}-lambda-arn

  ECRRepositoryUri:
    Condition: CreateECRCondition
    Description: URI of the ECR repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RAGLambdaECR}
    Export:
      Name: !Sub ${ProjectName}-ecr-uri

  ApiGatewayUrl:
    Description: Base URL of the API Gateway endpoint
    Value: !Sub https://${RAGRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStage}
    Export:
      Name: !Sub ${ProjectName}-api-url

  QueryEndpoint:
    Description: URL for submitting queries
    Value: !Sub https://${RAGRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStage}/query

  StatusEndpoint:
    Description: URL for checking job status
    Value: !Sub https://${RAGRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStage}/status/{jobId}

  HealthEndpoint:
    Description: URL for health checks
    Value: !Sub https://${RAGRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStage}/health

  JobStatusTableName:
    Description: Name of the DynamoDB table for job status
    Value: !Ref JobStatusTable
    Export:
      Name: !Sub ${ProjectName}-job-status-table

  RestApiId:
    Description: ID of the REST API
    Value: !Ref RAGRestApi
    Export:
      Name: !Sub ${ProjectName}-rest-api-id